# Generated by Django 2.0.7 on 2018-07-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(editable=False)),
                ('fileupload', models.FileField(upload_to=None, verbose_name='fileupload')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(choices=[(-1, 'All Users'), (0, 'Loggedin Users'), (1, 'Members of the Group'), (2, 'Staff Members'), (3, 'Nobody')])),
                ('edit', models.IntegerField(choices=[(-1, 'All Users'), (0, 'Loggedin Users'), (1, 'Members of the Group'), (2, 'Staff Members'), (3, 'Nobody')])),
            ],
        ),
        migrations.CreateModel(
            name='WikiSnip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created', models.DateTimeField(editable=False)),
                ('changed', models.DateTimeField(editable=False)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wikisnip_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wikisnip_edited', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Group')),
            ],
        ),
        migrations.CreateModel(
            name='WikiSnipChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField()),
                ('message', models.TextField()),
                ('change_type', models.IntegerField()),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sphwiki.WikiSnip')),
            ],
        ),
        migrations.AddField(
            model_name='wikipreference',
            name='snip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sphwiki.WikiSnip'),
        ),
        migrations.AddField(
            model_name='wikiattachment',
            name='snip',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sphwiki.WikiSnip'),
        ),
        migrations.AddField(
            model_name='wikiattachment',
            name='uploader',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
